import pandas as pd
import matplotlib.pyplot as plt
import os

# Path to the Excel file generated by your OI data script
excel_filename = "oi_data_{}.xlsx".format(pd.Timestamp.today().strftime('%Y%m%d'))

if not os.path.exists(excel_filename):
    print(f"File {excel_filename} not found in current directory.")
    exit(1)

# Read all sheet names (each is a strike/symbol)
xls = pd.ExcelFile(excel_filename)
sheet_names = xls.sheet_names

for sheet in sheet_names:
    df = pd.read_excel(xls, sheet_name=sheet)
    if 'opnInterest' not in df.columns or 'fetch_time' not in df.columns:
        print(f"Skipping {sheet}: missing 'opnInterest' or 'fetch_time' column.")
        continue
    # Sort by fetch_time in case not already sorted
    df = df.sort_values('fetch_time')
    # Plot change in open interest
    plt.figure(figsize=(10, 5))
    plt.plot(pd.to_datetime(df['fetch_time']), df['opnInterest'], marker='o')
    plt.title(f"Change in Open Interest for {sheet}")
    plt.xlabel("Time")
    plt.ylabel("Open Interest")
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(f"oi_change_{sheet}.png")
    plt.close()
    print(f"Saved OI change plot for {sheet} as oi_change_{sheet}.png")

print("All plots generated.")
